### ISSUE TITLE
Whole Team - Project Plan - What is the biggest unkonwn/risk?

### ISSUE THREAD

**Issue by pjdiiori** [pjdiiori/test_reusable_stories#141]
## Background
Goal: Make sure the entire team understand the biggest unknowns and/or biggest risks in this project, based on the current end of contract.

After the first call with the product owner, *everyone* on the team should spend 5 minutes writing down a comment on this ticket describing what they consider to be THE biggest unknown or risk about shipping this project. The PM will then guide a conversation to reach consensus on the #1 risk, and stub out a feature ticket to address that risk and prioritize highly with the Product Onwer.

## Scenario: Document the biggest risk
- GIVEN I am a member of the proejct team
- AND the first call with the product owner is complete
- [ ] WHEN I spend 5 minutes adding a comment that describes what I consider to the biggest risk on this project
- [ ] THEN my comment is added to the mix

## Scenario: Decide on #1 risk
- GIVEN everyone on the team has addded their comment
- AND I am acting PM on the project
- [ ] WHEN I facilitate a converation to reach consensus on the #1 risk
- [ ] THEN the team agrees on the #1 risk

## Scenario: Add feature story that addresses the #1 risk
- GIVEN the team has consensus on the #1 risk
- AND I am acting PM on the project
- [ ] WHEN I write and post a feature story address the #1 risk
- [ ] THEN the Product Owner can prioritize the story
