### ISSUE TITLE
Revelry - Time Tracking - Setup RevTime Project

### ISSUE THREAD

**Issue by pjdiiori** [pjdiiori/test_reusable_stories#19]
## Background
[RevTime](https://time.revelry.co/) is the time tracking tool currently used at Revelry. If a project has not yet been setup, then create a new project inside of [RevTime New Project Form](https://time.revelry.co/project/new).   Ping Thomas and ask what tags should be added to ensure correct tracking for tax credits.

## Scenario: Look for Project in RevTime
Given I am a Reveler
- [ ] When I log my hours
- [ ] Then I see the new project
- [ ] When I do not see the new project
- [ ] Then I fill out the [RevTime New Project Form](https://time.revelry.co/project/new)
